spring.application.name=wagerpilot


spring.datasource.url=jdbc:mysql://localhost:3306/wagerpilot
spring.datasource.username=root
spring.datasource.password=elton123

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true